### ISSUE TITLE
Shim for map

### ISSUE THREAD

**Issue by btd** [nodeca/plurals-cldr#1]
Hello.
I am babelfish user. I noticed, even if readme page states that it should be used with polyfill, single missing polyfill it requred it is Array.prototype.map from [lines](https://github.com/nodeca/plurals-cldr/blob/master/support/add.tpl#L10-L11). If i will make PR with simple function `map` that shim Array.prototype.map, will you accept it?

**Comment by btd** [comment]
Nevermind, i noticed also indexOf. Issue does not makes sense. Sorry for bothering.

**Comment by puzrin** [comment]
https://github.com/es-shims/es5-shim

I'd prefer to use well known shim instead of adding es3 kludges to code. That keeps code much more clear.
