### ISSUE TITLE
Any plans to update this module to cldr rules v40

### ISSUE THREAD

**Issue by jamuhl** [nodeca/plurals-cldr#3]
There are a few changes that might be worth updating this module to the latest v40.

Eg. french has now beside "one, other" also the "many" category.

Would be awesome if you find the time to get an update out to the npm registry. Thanks a lot for providing this module.

**Comment by puzrin** [comment]
released 2.0.0

**Comment by jamuhl** [comment]
awesome...thanks a lot 👍

**Comment by puzrin** [comment]
No problem, thank you for reminder about notable changes in CLDR.

Could you tell, how do you use this lib? It's very "low level". Usually people prefer more high abstraction, something like [babelfish](https://github.com/nodeca/babelfish).

**Comment by jamuhl** [comment]
We rely on the `plural.forms(lng)` function in our application which does basically add text fields needed for pluralforms in the target language based on the source language.

**Comment by puzrin** [comment]
Thanks!
