### ISSUE TITLE
Exposing the `test_data.json` from a library

### ISSUE THREAD

**Issue by timofei-iatsenko** [nodeca/plurals-cldr#9]
I found myself in the situation when the samples in the `test_data.json` might be very useful for [lingui.dev](https://lingui.dev/)

In one of our formatters, we have a challenge to convert Plural-Forms header supplied in the PO file and map it to the CLDR categories. 

To do so, we need "samples" for each CLDR category, so we can pass it to the gettext's Plural-Forms expression and map the result.

Unfortunately, I didn't find any ready to use library which have such information. 

Luckily, you're already preparing samples for your tests and this is exactly what we need.

It would be really nice to have this exposed, i think simply put this file as `.dist/samples.json` would be enough.

**Comment by puzrin** [comment]
IMHO that's out of scope. Pluralizers and testing are completely different tasks, and I would not like to mix.

**Comment by timofei-iatsenko** [comment]
Look at that not as for testing, but as exposing samples from CLDR data, something like [gettext-plurals](https://github.com/alexanderwallin/node-gettext/blob/master/lib/plurals.js) do: 

```js
ach: {
        name: 'Acholi',
        examples: [{
            plural: 0,
            sample: 1
        }, {
            plural: 1,
            sample: 2
        }],
        nplurals: 2,
        pluralsText: 'nplurals = 2; plural = (n > 1)',
        pluralsFunc: function(n) {
            return (n > 1);
        }
    },
    af: {
        name: 'Afrikaans',
        examples: [{
            plural: 0,
            sample: 1
        }, {
            plural: 1,
            sample: 2
        }],
        nplurals: 2,
        pluralsText: 'nplurals = 2; plural = (n !== 1)',
        pluralsFunc: function(n) {
            return (n !== 1);
        }
    },
```

This piece of information: 

```js
examples: [{
            plural: 0,
            sample: 1
        }, {
            plural: 1,
            sample: 2
        }],
```

is particularly helpful to do a matching/mapping between different implementations.

**Comment by puzrin** [comment]
Yes, test samples are part of CLDR data. IMHO you could take those directly from CLDR.
